# 示例配置：ViT Large + LoRA 只微调 MLP
defaults:
  - config

exp: dinov3_vit_large_lora_mlp

dinov3:
  backbone_type: vit
  model_path: /data/wly/ckpt/dinov3_vitl16 /model.safetensors
  pooling: gap
  head_type: linear
  
  use_lora: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  lora_modules: ['mlp']  # 只微调 MLP 模块

