# 示例配置：Swin-T Tiny + Multiscale 融合
defaults:
  - config

exp: swin_tiny_multiscale

dinov3:
  backbone_type: swin-t
  model_name: swin_tiny_patch4_window7_224
  pretrained: true
  pooling: multiscale
  head_type: mlp
  
  multiscale_layers: [1, 2, 3]  # Swin-T 有4个 stage，默认提取后3个 stage 的特征
  
  head_kwargs:
    hidden_dims: [1536, 768]  # embed_dim * 2, embed_dim (Swin-T Tiny 的 embed_dim 是 768)
  
  freeze_backbone: false

