# 示例配置：ConvNeXt + Multiscale
defaults:
  - config

exp: dinov3_convnext_multiscale

dinov3:
  backbone_type: convnext
  pooling: multiscale
  
  multiscale_layers: [1, 2, 3]
  
  head_kwargs:
    hidden_dims: [3072, 1536]  

