defaults:
  - config

exp: dinov3_vit_large_attention

dinov3:
  backbone_type: vit 
  model_path: /data/wly/ckpt/dinov3_vitl16 /model.safetensors
  pooling: attention 
  head_type: linear
  
  head_kwargs:
    num_heads: 8  
    hidden_dim: null  

