defaults:
  - config

exp: dinov3_vit_large_multiscale

dinov3:
  backbone_type: vit  # 使用 ViT Large
  model_path: /data/wly/ckpt/dinov3_vitl16 /model.safetensors
  pooling: multiscale  
  head_type: linear
  
  multiscale_layers: [6, 12, 18, 23]
  
  head_kwargs:
    hidden_dims: [2048, 1024] 

